### ISSUE TITLE
any chance for a chrome version?

### ISSUE THREAD

**Issue by TheDeepNate** [atresnjo/Wox.Plugin.BrowserTabFinder#1]
This would be great for chrome too, any chance in the future to add chrome?

**Comment by atresnjo** [comment]
Hey, sure. I'll take a look at Chrome soon.

**Comment by atresnjo** [comment]
@TheDeepNate 

I just uploaded the new version, you should be able to update it as usual in wox by typing "wpm install Browser Tab Finder" .. this was only tested on my machine with the latest chrome version, so feel free to report back if it works for you.

![2018-09-01_18-10-56](https://user-images.githubusercontent.com/41112852/44948036-b55bb580-ae16-11e8-8dca-9a53b050be36.gif)

**Comment by TheDeepNate** [comment]
This works great! Thank you very much.

**Comment by atresnjo** [comment]
@TheDeepNate 

Missed that one, good catch. I added a setting option which you can enable to maximize the browser instance when clicking a tab. Updated the plugin on wox.
